[package]
name = "housing_viz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "data_collection"
path = "src/data_collection/sync/main.rs"
