version: '3.1'

services:
  database:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - "./.mongo-data:/data/db"

  scraping:
    build: .
    command: ["go", "run", "cmd/scraping/main.go"]
    container_name: scraping-container
    environment:
      - MAPS_API_KEY=${MAPS_API_KEY}
      - MONGODB_URI=${MONGODB_DOCKER_URI}
      - DOCKER=TRUE
    depends_on:
      - database
    links:
      - database:database

  website:
    build: .
    command: [ "go", "run", "cmd/web/main.go" ]
    container_name: website-container
    environment:
      - MONGODB_URI=${MONGODB_DOCKER_URI}
      - MAPS_API_KEY=${MAPS_API_KEY}
      - DOCKER=TRUE
    depends_on:
      - database
    links:
      - database:database
    ports:
      - "8080:8080"
