version: '3.1'

services:
  database:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - "./mongo-data:/data/db"

  scraping:
    image: golang
    container_name: scraping
    environment:
      - MAPS_API_KEY=${MAPS_API_KEY}
      - MONGODB_URI=${MONGODB_URI}
      - DOCKER=TRUE
